[package]
name = "vectorize"
version = "0.0.1"
edition = "2021"
publish = false

[lib]
crate-type = ["cdylib"]

[features]
default = ["pg15"]
pg11 = ["pgrx/pg11", "pgrx-tests/pg11"]
pg12 = ["pgrx/pg12", "pgrx-tests/pg12"]
pg13 = ["pgrx/pg13", "pgrx-tests/pg13"]
pg14 = ["pgrx/pg14", "pgrx-tests/pg14"]
pg15 = ["pgrx/pg15", "pgrx-tests/pg15"]
pg_test = []

[dependencies]
anyhow = "1.0.72"
chrono = {version = "0.4.26", features = ["serde"] }
log = "0.4.19"
pgmq = "0.13.0"
pgrx = ">=0.8.0"
postgres-types = "0.2.5"
reqwest = {version = "0.11.18", features = ["json"] }
serde = "1.0.173"
serde_json = "1.0.103"
sqlx = {version = "0.7.1", features = [ "runtime-tokio-native-tls" , "postgres", "chrono", "json" ] }
thiserror = "1.0.44"
tokio = "1.29.1"

[dev-dependencies]
pgrx-tests = ">=0.9.8"

[profile.dev]
panic = "unwind"

[profile.release]
panic = "unwind"
opt-level = 3
lto = "fat"
codegen-units = 1
