[extension]
name = "pg_vectorize"
repository = "https://github.com/tembo-io/pg_vectorize"
license = "PostgreSQL"
description = "The simplest implementation of LLM-backed vector search on Postgres."
homepage = "https://github.com/tembo-io/pg_vectorize"
documentation = "https://github.com/tembo-io/pg_vectorize"
categories = ["orchestration", "machine_learning"]
version = "0.0.1"

[build]
postgres_version = "15"
platform = "linux/amd64"